RA-13 Recipe screen without calculating
alexanderporublev/AndroidSprint pull request #11
Opened 2024-10-08 10:52 UTC by alexanderporublev

2024-10-09 06:24 UTC, ievetrovdev requested changes
Предлагаю еще держать в актуальном состоянии версию Android Studio (регулярно чекать по toolbox и обновляться до последней стабильной). 

А также обновлять AGP, так, например, у меня более свежая версия всего этого и просто не могу собрать проект. Точно также надо думать о своих тиммейтах. Но в компании обновлять все эти вещи правильнее в отдельной ветке, чтобы не было конфликтов.

2024-10-09 06:24 UTC, ievetrovdev commented on gradle/libs.versions.toml
> +androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
а для чего понадобилась эта строка?

2024-10-09 06:24 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_24">24sp</dimen>
Давай визуально разделим шрифт от других размеров

2024-10-09 06:27 UTC, ievetrovdev requested changes
Ну и пропали ресурсы. Проверяй ветку перед отправкой (либо это баг, но надо пофиксить)

<img width="846" alt="Снимок экрана 2024-10-09 в 09 27 16" src="https://github.com/user-attachments/assets/dd06828d-1c78-44b2-833a-c94335288c4b">

2024-10-09 06:27 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="text_24">24sp</dimen>
Также не рекомендуется повторять значения ресурсов. Только уникальные оставляем

    <dimen name="corner_radius">8dp</dimen>
    <dimen name="half_margin">8dp</dimen>

2024-10-11 16:43 UTC, ievetrovdev reviewed
Сейчас рецепт не соответствет дизайну из Фигмы. У тебя все буквы капсом, нету точки после списка, отсутствуют девайдеры между элементами
![image](https://github.com/user-attachments/assets/833a87f2-1f21-414f-947c-439ef13231fe)

2024-10-11 16:43 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            tools:listitem="@layout/item_recipe" />
Здесь нужно использовать item_ingredient, чтобы корректно все отображалось на макете

2024-10-11 16:43 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:scaleType="centerCrop" />
Заполни тестовыми данными шапку тоже

2024-10-11 16:43 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +        android:layout_weight="0" />
Сюда тоже добавь тестовые данные

2024-10-11 16:43 UTC, ievetrovdev commented on app/src/main/res/layout/item_method.xml
> +        style="@style/StyleTitle14Gray" />
тестовые даныне

2024-10-11 16:43 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_marginVertical="@dimen/half_margin"
Можно просто использовать margin в таких случаях

2024-10-11 16:43 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +        <com.google.android.material.divider.MaterialDivider
Здесь MaterialDivider не нужен. Мы должны реализовать его между каждым элементом списка, как на дизайне в фигме. Глянь ссылку из пункта 7, там пример приведен реализации

2024-10-16 15:38 UTC, ievetrovdev requested changes

2024-10-16 15:38 UTC, ievetrovdev commented on app/src/main/java/ru/redsoft/androidsprint/RecipeFragment.kt
> +                    it.dividerColor = context?.resources?.getColor(R.color.background_color)?:Color.BLACK
Такой способ получения цвета устаревший, используй getColor(int, Resources.Theme?). Также цвет не как из дизайна, он практически полностью сливается с задним фоном

2024-10-16 15:38 UTC, ievetrovdev commented on app/src/main/java/ru/redsoft/androidsprint/RecipeFragment.kt
> +                    it.dividerThickness = 1
Также divider не должен применяться к последнему элементу и занимать всю длину объекта. Настрой корректно эти параметры
dividerInsetStart 
dividerInsetEnd 
isLastItemDecorated

2024-10-16 15:38 UTC, ievetrovdev commented on app/src/main/java/ru/redsoft/androidsprint/RecipeFragment.kt
> +            MaterialDividerItemDecoration(binding.rvMethod.context, MaterialDividerItemDecoration.VERTICAL).also {
Ты создаешь идентичные объекты здесь и выше, почему бы не вынести в отдельную переменную его и переиспользовать в двух местах? Код станет  чище и оптимизированее

2024-10-16 15:38 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@color/white"
Глянь дизайн в фигме, края у задника сглаженные. Сделай по аналогии с задником текста шапки

2024-10-16 19:58 UTC, Churickoid approved these changes
Молодец, по основной задаче проблем нет! Оставил пару небольших комментов на исправление, поправь в следующем ПР

2024-10-16 19:58 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/RecipeFragment.kt
> +                divider.dividerInsetStart = 0
Отступы от краев ты прописал, но они нулевые. По дизайну в фигме оно заполняет не всю длину. Пропиши корректные отсутпы, чтоб соответствовало макету

2024-10-16 19:58 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@color/white"
Эту проблему из коммента так и не поправил, добавь как в тексте шапки background:
android:background="@drawable/rounded_rectangle_shape"

2024-10-17 09:20 UTC, merged