RA-28 Jetpack Navigation
alexanderporublev/AndroidSprint pull request #24
Opened 2024-11-09 09:13 UTC by alexanderporublev

Из прошлого замечания осталось непонятно как обработчик клика перенести в метод observe

2024-11-09 21:23 UTC, Churickoid commented
> Из прошлого замечания осталось непонятно как обработчик клика перенести в метод observe

Не совсем понял вопрос. Можешь подробнее? Просто листенер устанавливать внутри observer, если требуется данные из него

2024-11-10 13:48 UTC, alexanderporublev commented
> > Из прошлого замечания осталось непонятно как обработчик клика перенести в метод observe
> 
> Не совсем понял вопрос. Можешь подробнее? Просто листенер устанавливать внутри observer, если требуется данные из него

Перенес установку листенера в observer, но не понимаю плюса этого решения, поскольку раньше листенер устанавливался один раз при создании аюдаптера, а теперь он создается и устанавливается при каждом изменении списка категорий

2024-11-10 18:51 UTC, Churickoid requested changes

2024-11-10 18:51 UTC, aGroupoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoriesListFragment.kt
> +            findNavController().navigate(R.id.recipesListFragment, bundle)
Фрагменты между собой должны перемещаться через action, для этого в nav_graph нужно соединить стрелочками, там где надо. Студия сгенерирует нужный action
Для action можно прописать параметр app:launchSingleTop="true", так фрагмент будет открываться лишь единожды. 
Все переходы между фрагментами должны выполняться через action, а не напрямую

Попробуй 10 раз подряд нажать на кнопку Категорий, все они попадут в backstack, чтобы их все закрыть придется нажать 10 раз на кнопку назад. Для action можно прописать параметр app:launchSingleTop="true", но для фрагментов из MainActivity это не сработает, поскольку они без action. Придется сделать по другому, создать navOptions и прописать эти настройки
![image](https://github.com/user-attachments/assets/f1951d74-d55a-436d-9e3d-dcc53f653b92)

2024-11-10 18:56 UTC, Churickoid commented
> Перенес установку листенера в observer, но не понимаю плюса этого решения, поскольку раньше листенер устанавливался один раз при создании аюдаптера, а теперь он создается и устанавливается при каждом изменении списка категорий

Основной плюс - это мы ссылаемся на единственные актуальные данные, наш стейт.  Ссылаться на разные источники данных может привести к их рассинхрону. В нашем проекте стейт рецептов не меняется после первой загрузки, но всё же, лучше сразу привыкать к правильному подходу. А то что переменная меняет свое значение, хоть это и лямбда - незначительная операция, ей можно пренебречь для благой цели.

Вчера остался коммент на удержании, только щас отобразился. Поправь его

2024-11-14 12:50 UTC, Churickoid approved these changes
В целом всё верно, молодец!
Сейчас такой баг - понажимай 10 раз на кнопку категорий, все они попадут в backstack. Пользователю придется 10 раз нажимать назад, чтоб очистить. На скрине я привел конструкцию как это можно пофиксить в mainActivity, реализуй её в следующем ПР

2024-11-14 13:49 UTC, merged