RA-39 category list cache
alexanderporublev/AndroidSprint pull request #34
Opened 2024-11-28 12:29 UTC by alexanderporublev

![deviceexplorer](https://github.com/user-attachments/assets/54627fc0-5126-48ce-9032-1982f14a33c7)

2024-11-28 19:44 UTC, Churickoid requested changes

2024-11-28 19:44 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/dependency.kt
> +object dependency {
Классы мы называем всегда с большой буквы

2024-11-28 19:44 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/dependency.kt
> +    var context: Context? = null
Я бы вообще от этого класса отказался. Application является контекстом, мы его можем получить в любом андроид-объекте и так. Достаточно только грамотно его передавать в нужные места. А эта переменная может привести к проблемам, поскольку ApplicationContext отличается от ActivityContext и не понятно какой будет лежать здесь при обращении

2024-11-28 19:44 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
>              synchronized(mutex) {
Мы уже перешили на корутины, давай уже использовать mutex.withLock. И тогда лучше на всю функцию init а не только при изменении стейта, postValue потоко-безопасный, именно ему мютекс и не нужен

2024-11-28 19:44 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/data/network/RecipesRepository.kt
> +        dependency.context?:throw IllegalStateException("Not any context provided"),
Чтобы получить здесь контекст, достаточно просто передавать его в конструктор репозитория. Так код станет менее зависимым и для юнит-тестов этот котнекст легко можно будет подменить, пробросив тестовую заглушку в конструткор

2024-11-28 19:44 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +            categories?.forEach {
Сейчас кеширование не работает. Его основная суть, чтобы список работал с выключенным интернетом. Если выключить интернет, categories становится null и твой блок forEach не выполнится из-за .?

2024-12-12 12:21 UTC, aGroupoid requested changes

2024-12-12 12:21 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +            mutex.withLock {
Мютекс должен использоваться для сетевых функций getCategoriesFromCache и getAllCategories. На postValue он не нужен, там под копотом и так потокобезопасная инициализация

2024-12-12 12:21 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +                cache += it
Надо переработать эту логику. Сейчас у тебя при включенном интернете список отображается дважды. Сначала кэшированный, ниже - сетевой. Также при выключенном интернете данные из кэша доходят, а сообщение об ошибке тоже вылазиет. Предлагаю делать интернет-запрос только при пустом кэше и ошибку показывать если кэш пустой и интернет выключен

2024-12-13 07:06 UTC, Churickoid requested changes

2024-12-13 07:06 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +            }
Поток будет ожидать, пока все что внутри mutex не выполнится, разделять на две разных лямбды - нет смысл

2024-12-13 07:06 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +                cache.clear()
Непонятно, зачем брать кеш из базы данных (длительная операция), а затем его очищать. У нас в проекте данные не обновляются на сервере. Но если представть, что кэш может устаревать, то тогда мы должны делать сетевой запрос, если доступа нет - только тогда обращаться к кэшу, если и он пуст то выводим ошибку. Сейчас эта логика не оптимизирована

2024-12-13 07:12 UTC, alexanderporublev commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +                cache.clear()
В задании написано:

Поменять логику получения категорий CategoriesListViewModel:
Сначала запросить данные из кэша, потом через бэкенд.
Полученные через бэкенд данные записать в базу.

2024-12-13 14:18 UTC, Churickoid commented on app/src/main/java/ru/redsoft/androidsprint/ui/category/CategoryListViewModel.kt
> +                cache.clear()
Ок, по заднию имелось ввиду, что необходимо сначала делать кеш, только при его отсутствии - запрашивать из сети и заполнять кэш. Иначе никакого смысла в кэшировании нет. Его же суть в том, что не придется лишний раз ходить в сеть

2024-12-13 14:30 UTC, aGroupoid approved these changes
В целом можешь оставить как сейчас реализацию, апрув. Сейчас суть кэша видна, до этого было что-то непонятно

2024-12-15 07:31 UTC, merged