RA-07 category list layout
alexanderporublev/AndroidSprint pull request #5
Opened 2024-09-03 15:49 UTC by alexanderporublev

2024-09-03 20:16 UTC, ievetrovdev requested changes

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_categories_list.xml
> +            android:scaleType="center"
Фото не все пространство занимает, белые полосы по бокам. Укажи другой scaleType

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="200dp"
Давай заполним данные тестовыми данными любой категории. Это можно сделать через атрибут tools. Наша задача сейчас понять, как это примерно выглядит на превью в студии.

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +        android:layout_height="match_parent">
Не забывай применять автоформатирование. В том числе и в разметках. Когда все атрибуты стоят на своих местах (в порядковом смысле) - со временем привыкаешь и быстро ориентируешься при их считывании.

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_categories_list.xml
> +        tools:listitem="@layout/item_category" />
Когда заполнишь тестовыми данными, сравни с макетом из фигмы на этом экране, увидишь проблемы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +        android:padding="4dp"
Не забывай все значения размеров выносить в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="corner_radius">8dp</dimen>
значения ресурсов не дублируем

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">#5F3678</item>
цвета выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">20sp</item>
значения выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
>          <item name="cornerRadius">8dp</item>
значения выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
>          <item name="android:textSize">14sp</item>
значения выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">#5F3678</item>
цвета выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textColor">#666666</item>
цвета выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">16sp</item>
значения выносим в ресурсы

2024-09-03 20:16 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">12sp</item>
значения выносим в ресурсы

2024-09-04 08:59 UTC, alexanderporublev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">16sp</item>
Не до конца понятно зачем из стиля размер текста в ресурсы выносить и какое наименование давать

2024-09-05 17:42 UTC, ievetrovdev commented
Попробуй расширить макет в студии, на больших экранах список не соответствует дизайну. Это связано с тем, что карточки занимают wrap_content пространство, а не всё возможное

2024-09-05 17:44 UTC, ievetrovdev commented
![image](https://github.com/user-attachments/assets/9c0a3dc5-d1ae-4853-b15c-95c59c56e4c4)

2024-09-05 18:02 UTC, ievetrovdev requested changes

2024-09-05 18:02 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    app:layout_constraintTop_toTopOf="parent">
Эти параметры ничего не делают, их можно спокойно убрать. Они работают только внутри ConstraintLayout

2024-09-05 18:02 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">16sp</item>
Стиль названия ресурсов в приложении обычно скорее придумывается, чем берется какое-либо эталонный стиль. Существуют разные подходы. text_12 text_14 и тд вполне нормальные названия. Можно добавить еще text_small_12 text_medium_14 
Если потребуется быстро во всём приложение для надписей с размер 12 поменять размер на 8,  то достаточно поменять в dimens файле значение, а не выискивать по всему проекту эти места. То что в названии фигурирует число 12,  это не проблема, через Shift+F6 можно отрефакторить на новое название. Это один из главных плюсов вынесения в ресурсы

2024-09-06 20:32 UTC, ievetrovdev requested changes

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            tools:ignore="RtlSymmetry"
Студия ругается, что с paddingStart появляется ассиметрия. Также если глянешь макет, то увидишь, что padding с двух сторон у текста сразу. Будет соответсвовать дизайну и проблему угнорировать не придется.

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:paddingBottom="@dimen/margin"
Не обязательно для каждой стороны прописывать педдинги по отдельности. Есть более универсальные атрибуты.
android:paddingHorizontal=""
android:paddingVertical=""

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="130dp"
лучше вынести в dimens

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            tools:ignore="RtlSymmetry"
<img width="321" alt="Снимок экрана 2024-09-06 в 23 26 24" src="https://github.com/user-attachments/assets/4f6d0b00-deed-4055-a74a-8696c3e267a9">

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_categories_list.xml
> +            android:src="@drawable/bcg_categories" />
Не забудь добавить “описание контента”. contentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов. Достаточно передать смысл изображения, например "Изображение категорий"

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:scaleType="centerCrop"
А здесь не обязателен сontentDescription, можно добавить tools:ignore="ContentDescription". Поскольку картинка будет динамической, сontentDescription будем ставить в самом коде

2024-09-06 20:32 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_categories_list.xml
> +        android:layout_height="224dp">
это тоже в ресурсы

2024-09-07 17:22 UTC, ievetrovdev approved these changes
Молодец, теперь всё корректно. Приступай к новому заданию

2024-09-08 08:16 UTC, merged